<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Question Response Entity.
 *
 * Represents a single answer to a question within a survey response. This entity
 * stores the actual response data for different question types.
 *
 * Relationships:
 * - Many-to-One with SurveyResponse entity
 * - Many-to-One with Question entity
 *
 * @author navneet0693
 *
 * @ORM\Entity(repositoryClass="App\Repository\QuestionResponseRepository")
 *
 * @ORM\Table(name="question_responses")
 */
#[ORM\Entity(repositoryClass: 'App\Repository\QuestionResponseRepository')]
#[ORM\Table(name: 'question_responses')]
class QuestionResponse
{
    /**
     * Unique identifier for the question response
     * Auto-generated by Doctrine ORM.
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer', nullable: false)]
    private int $id;

    /**
     * The survey response this question response belongs to
     * Required relationship - question responses cannot exist without a survey response.
     */
    #[ORM\ManyToOne(targetEntity: SurveyResponse::class, inversedBy: 'questionResponses')]
    #[ORM\JoinColumn(nullable: false)]
    private SurveyResponse $surveyResponse;

    /**
     * The question this response answers
     * Required relationship - responses must be linked to a specific question.
     */
    #[ORM\ManyToOne(targetEntity: Question::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Question $question;

    /**
     * Selected option IDs for choice questions
     * JSON array containing IDs of selected QuestionOption entities
     * Used for single choice and multiple choice questions.
     */
    #[ORM\Column(type: 'json', nullable: true)]
    private ?array $selectedOptionIds = null;

    /**
     * Timestamp when the response was created
     * Auto-set in constructor.
     */
    #[ORM\Column(type: 'datetime')]
    private \DateTime $createdAt;

    /**
     * Constructor initializes timestamp
     * Sets creation timestamp to current time.
     */
    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * Get the unique identifier of the question response.
     *
     * @return int|null The response ID, null if not persisted
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Get the survey response this question response belongs to.
     *
     * @return SurveyResponse The parent survey response
     */
    public function getSurveyResponse(): SurveyResponse
    {
        return $this->surveyResponse;
    }

    /**
     * Set the survey response this question response belongs to.
     *
     * @param SurveyResponse $surveyResponse The parent survey response
     *
     * @return self For method chaining
     */
    public function setSurveyResponse(SurveyResponse $surveyResponse): self
    {
        $this->surveyResponse = $surveyResponse;

        return $this;
    }

    /**
     * Get the question this response answers.
     *
     * @return Question The question being answered
     */
    public function getQuestion(): Question
    {
        return $this->question;
    }

    /**
     * Set the question this response answers.
     *
     * @param Question $question The question being answered
     *
     * @return self For method chaining
     */
    public function setQuestion(Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    /**
     * Get the selected option IDs for choice questions.
     *
     * @return array|null Array of selected option IDs, null if not applicable
     */
    public function getSelectedOptionIds(): ?array
    {
        return $this->selectedOptionIds;
    }

    /**
     * Set the selected option IDs for choice questions.
     *
     * @param array|null $selectedOptionIds Array of selected option IDs
     *
     * @return self For method chaining
     */
    public function setSelectedOptionIds(?array $selectedOptionIds): self
    {
        $this->selectedOptionIds = $selectedOptionIds;

        return $this;
    }

    /**
     * Get the creation timestamp.
     *
     * @return \DateTime The creation timestamp
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * Set the creation timestamp.
     *
     * @param \DateTime $createdAt The creation timestamp
     *
     * @return self For method chaining
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Check if this response has any data.
     */
    public function hasResponse(): bool
    {
        return !empty($this->selectedOptionIds);
    }
}
